### PR TITLE
Added my miner code

### PR DESCRIPTION
**Pull request by Luca0208**
Added some code from my KST miner, you are free to modify it to your needs.

### CODE REVIEW

**Comment by Luca0208** [comment]
I just noticed that I put the stuff for the compiling in there too, you can remove everything except src.

**Comment by bauen1** [comment]
You can change it by making a commit to your fork i think.

**Comment by bauen1** [comment]
Ooops

**Comment by Luca0208** [comment]
Something went really wrong, give me a second to fix GitHub desktop

**Comment by bauen1** [comment]
Actually Let me make another repository for this miner, ok?

**Comment by Luca0208** [comment]
Ok

**Pull request closed without merging**
